### ISSUE TITLE
[CONTROLLER] Ошибка при входе несуществующим пользователем

### ISSUE THREAD

**Issue by anry-das** [group52/OnlineJournal#9]
При попытке войти пользователем, которого нет в БД получаем ошибку:

> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.group53.dao.UserDAOImpl.validateUser(UserDAOImpl.java:33)
	at com.group53.dao.UserServiceImpl.validateUser(UserServiceImpl.java:16)
	at com.group53.controllers.LoginController.loginProcess(LoginController.java:32)

Это нужно исправить.
Кроме того в случае любой ошибки необходимо перенаправлять пользователя на страницу ошибок (п.24) - #8

**Comment by group52** [comment]
e8169c5
